# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["dev"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_ROOT_PASSWORD: test

    steps:
      - uses: actions/checkout@v2

      - name: Run backend tests
        env:
          BACKEND_PORT: 5000
          DB_TYPE: postgres
          DB_HOST: localhost
          DB_PORT: 5432
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: postgres
          JWT_SECRET: secret
          JWT_TIMING: 1h

        run: |
          cd api
          npm install
          npm run test
