# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: ["dev"]

jobs:
  backend-tests:
    runs-on: ubuntu-latest

    services:
      api_mariadb:
        image: mariadb
        ports:
          - 3306:3306
        env:
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: test

    steps:
      - uses: actions/checkout@v2

      - name: Run backend tests
        env:
          BACKEND_PORT: 5000
          FRONTEND_URL: http://localhost:3000
          DB_TYPE: mariadb
          DB_HOST: localhost
          DB_PORT: 3306
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: test
          JWT_SECRET: secret
          JWT_TIMING: 1h

        run: |
          cd api
          npm install
          npm run test
